# Generated by Django 3.0 on 2025-05-16 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Inovacoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('empresa', models.CharField(blank=True, max_length=50, null=True)),
                ('repositorio', models.CharField(blank=True, max_length=100, null=True)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('areas', models.ManyToManyField(to='inovacoes.Areas')),
            ],
        ),
    ]
