# Generated by Django 3.0 on 2025-05-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projetos',
            old_name='ativo',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='projetos',
            old_name='data_fim',
            new_name='begin',
        ),
        migrations.RenameField(
            model_name='projetos',
            old_name='empresa',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='projetos',
            old_name='criado_em',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='projetos',
            old_name='descricao',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='projetos',
            old_name='data_inicio',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='projetos',
            old_name='repositorio',
            new_name='repository',
        ),
        migrations.RenameField(
            model_name='projetos',
            old_name='titulo',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='projetos',
            old_name='valor',
            new_name='value',
        ),
        migrations.AddField(
            model_name='projetos',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projetos',
            name='highlights',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projetos',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects_images/'),
        ),
        migrations.AddField(
            model_name='projetos',
            name='year',
            field=models.IntegerField(default=2025),
        ),
    ]
