# Generated by Django 3.0 on 2025-05-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_auto_20250528_0906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cursos',
            old_name='ativo',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='cursos',
            old_name='data_fim',
            new_name='begin',
        ),
        migrations.RenameField(
            model_name='cursos',
            old_name='criado_em',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='cursos',
            old_name='descricao',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='cursos',
            old_name='titulo',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='cursos',
            old_name='data_inicio',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='cursos',
            old_name='vagas',
            new_name='vacancies',
        ),
        migrations.AddField(
            model_name='cursos',
            name='format',
            field=models.CharField(default='Online', max_length=50),
        ),
        migrations.AddField(
            model_name='cursos',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courses_images/'),
        ),
        migrations.AddField(
            model_name='cursos',
            name='level',
            field=models.CharField(default='Iniciante', max_length=50),
        ),
        migrations.AddField(
            model_name='cursos',
            name='modules',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cursos',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='cursos',
            name='title',
            field=models.CharField(default='Curso', max_length=50),
        ),
    ]
